version: "3.7"

services:

  autorenew-mailserver-certs:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mailserver-traefik
    labels:
      - "traefik.frontend.rule=Host:mail.youtous.dv" # traefik ACME will handle creation of certificates for this domain
      - traefik.frontend.redirect.replacement=http://youtous.dv/ # redirect access to smtp/imap domain to and other domain (e.g. webmail)
      - traefik.frontend.redirect.regex=.*
      - traefik.port=8080 # dummy port, used only to trigger certificate renewal
      - traefik.enable=true
      - traefik.frontend.entryPoints=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TRAEFIK_VERSION=1
      - CERTS_SOURCE=consul
      - DOMAINS=mail.youtous.dv
      - COPY_METHOD=volume
    depends_on:
      - traefik

  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: youtous.dv
    container_name: mailserver
    ports:
      - "127.0.0.1:25:25"
      - "127.0.0.1:143:143"
      - "127.0.0.1:587:587"
      - "127.0.0.1:993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./.mailserver-config/:/tmp/docker-mailserver/
    env_file:
      - .mailserver.env

  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'

  traefik:
    image: traefik:v1.7
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    labels:
      - traefik.frontend.rule=Host:traefik.youtous.dv
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.entryPoints=http,https
      - traefik.frontend.redirect.entryPoint=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --docker
      --docker.watch
      --docker.exposedbydefault=false
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --consul
      --consul.endpoint="consul-leader:8500"
      --acme
      --acme.email=report@youtous.dv
      --acme.storage="traefik/acme/account"
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onhostrule=true
      --acme.acmelogging=true
      --logLevel=INFO
      --accessLog
      --api
    depends_on:
      - consul-leader

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
  consul-data-leader:
