logLevel = "DEBUG"

defaultEntryPoints = ["http", "https", "http5002challenge"]

[entryPoints]
  [entryPoints.http5002challenge]
  address = ":5002"
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "test@traefik.io"
entryPoint = "https"
onHostRule = true
storage = "/etc/traefik/conf/acme.json"
caServer = "http://traefik.boulder.com:4001/directory"
acmeLogging = true
  [acme.httpChallenge]
  entryPoint="http5002challenge"


[api]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.localhost.com"
watch = true
exposedByDefault = false


