logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "test@traefik.io"
entryPoint = "https"
onDemand = false
onHostRule = true
storage = "traefik/acme/account"
caServer = "http://traefik.boulder.com:4001/directory"
  [acme.httpChallenge]
  entryPoint="http"

[consul]
endpoint = "consul-leader:8500"

[api]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.localhost.com"
watch = true
exposedByDefault = false


