version: "2"

services :

### Autorenew docker-mailserver part
  autorenew-mailserver-certs:
    build:
      context: ./../
      dockerfile: Dockerfile
    container_name: mailserver-traefik
    labels:
      - "traefik.frontend.rule=Host:mail.youtous.dv" # traefik ACME will handle creation of certificates for this domain
      - traefik.frontend.redirect.replacement=http://youtous.dv/ # redirect access to smtp/imap domain to and other domain (e.g. webmail)
      - traefik.frontend.redirect.regex=.*
      - traefik.port=8080 # dummy port, used only to trigger certificate renewal
      - traefik.enable=true
      - traefik.frontend.entryPoints=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssl:/tmp/ssl
    environment:
      - TRAEFIK_VERSION=1
      - CERTS_SOURCE=consul
      - DOMAIN=mail.youtous.dv
      - KV_ENDPOINTS=[consul-leader:8500]
    depends_on:
      - traefik

  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: youtous.dv
    container_name: mailserver
    ports:
      - "127.0.0.1:25:25"
      - "127.0.0.1:143:143"
      - "127.0.0.1:587:587"
      - "127.0.0.1:993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./.mailserver-config/:/tmp/docker-mailserver/
    env_file:
      - .mailserver.env

### ACME part

  boulder:
    # To minimize fetching this should be the same version used below
    image: containous/boulder:containous-acmev2
    environment:
      FAKE_DNS: 172.17.0.1
      PKCS11_PROXY_SOCKET: tcp://boulder-hsm:5657
    restart: unless-stopped
    extra_hosts:
      - le.wtf:127.0.0.1
      - boulder:127.0.0.1
    ports:
      - 4000:4000 # ACME
      - 4001:4001 # ACMEv2
      - 4002:4002 # OCSP
      - 4003:4003 # OCSP
      - 4430:4430 # ACME via HTTPS
      - 4431:4431 # ACMEv2 via HTTPS
      - 4500:4500 # ct-test-srv
      - 6000:6000 # gsb-test-srv
      - 8000:8000 # debug ports
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
      - 8005:8005
      - 8006:8006
      - 8008:8008
      - 8009:8009
      - 8010:8010
      - 8055:8055 # dns-test-srv updates
      - 9380:9380 # mail-test-srv
      - 9381:9381 # mail-test-srv
    depends_on:
      - bhsm
      - bmysql
    networks:
      - default

  bhsm:
    # To minimize fetching this should be the same version used above
    image: letsencrypt/boulder-tools:2018-03-07
    hostname: boulder-hsm
    environment:
      PKCS11_DAEMON_SOCKET: tcp://0.0.0.0:5657
    command: /usr/local/bin/pkcs11-daemon /usr/lib/softhsm/libsofthsm2.so
    expose:
      - 5657
    networks:
      default:
        aliases:
          - boulder-hsm

  bmysql:
    image: mariadb:10.1
    hostname: boulder-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld --bind-address=0.0.0.0
    logging:
        driver: none
    networks:
      default:
        aliases:
          - boulder-mysql

  ## TRAEFIK part ##

  traefik:
    image: traefik:v1.7
    command: >
      --configFile=/etc/traefik/conf/acme.toml
      --consul
      --consul.endpoint="consul-leader:8500"
      --acme.storage="traefik/acme/account"
      --accessLog
      --api
    restart: unless-stopped
    extra_hosts:
      - traefik.boulder.com:172.17.0.1
    volumes:
      - "./acme.toml:/etc/traefik/conf/acme.toml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/etc/traefik/conf/acme.json:rw"
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "127.0.0.1:5001:443" # Needed for SNI challenge
      - "127.0.0.1:5002:80" # Needed for HTTP challenge
    expose:
      - "8080"
    labels:
      - "traefik.port=8080"
      - "traefik.backend=traefikception"
      - "traefik.frontend.rule=Host:traefik.youtous.dv"
      - "traefik.enable=true"
    depends_on:
      - boulder
      - consul-leader

  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    labels:
      - "traefik.frontend.rule=Host:consul.youtous.dv"
      - traefik.enable=true
      - traefik.port=8500
      - traefik.frontend.entryPoints=https

volumes:
  consul-data-leader:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local