version: "3.7"

services:

  ### Autorenew docker-mailserver part ###
  autorenew-mailserver-certs:
    build:
      context: ./../
      dockerfile: Dockerfile
    labels:
      - "traefik.frontend.rule=Host:mail.localhost.com" # traefik ACME will handle creation of certificates for this domain
      - traefik.frontend.redirect.replacement=http://localhost.com/ # redirect access to smtp/imap domain to and other domain (e.g. webmail)
      - traefik.frontend.redirect.regex=.*
      - traefik.port=8080 # dummy port, used only to trigger certificate renewal
      - traefik.enable=true
      - traefik.frontend.entryPoints=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./acme.json:/tmp/traefik/acme.json" # acme.json from Traefik
      - "./ssl:/tmp/ssl:rw" # dev only, todo remove
    environment:
      - TRAEFIK_VERSION=1
      - CERTS_SOURCE=file
      - DOMAIN=mail.localhost.com
    networks:
      bluenet:
        ipv4_address: 10.77.77.88

  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: localhost.com
    labels:
      - "mailserver-traefik-autorenew-domain=mail.localhost.com"
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./.mailserver-config/:/tmp/docker-mailserver/
      - ./.mailserver-config/dh-dovecot.pem:/etc/dovecot/dh.pem:ro # saving us computation
    env_file:
      - .mailserver.env
    networks:
      bluenet:
        ipv4_address: 10.77.77.44

  ### ACME test server ###
  pebble:
    image: letsencrypt/pebble
    command: pebble -config /test/my-pebble-config.json -dnsserver 10.77.77.22:8053
    ports:
      - 4001:4001  # ACME port
      - 15000:15000  # Management port
    environment:
      - PEBBLE_VA_NOSLEEP=1
    extra_hosts:
      - acme.localhost.com:10.77.77.77 # test ACME server (peeble)
    volumes:
      - ./peeble/certs/:/test/certs/:ro # import peeble RootCA
      - ./peeble/peeble-config.json:/test/my-pebble-config.json:ro
    networks:
      bluenet:
        ipv4_address: 10.77.77.77
    depends_on:
      - challtestsrv
  challtestsrv: # dns server for pebble
    image: letsencrypt/pebble-challtestsrv:latest
    command: pebble-challtestsrv -defaultIPv6 "" -defaultIPv4 10.77.77.66 # mock DNS responses to traefik
    ports:
      - 8055:8055  # HTTP Management API
    networks:
      bluenet:
        ipv4_address: 10.77.77.22

  ### Traefik part ###
  traefik:
    extra_hosts:
      - acme.localhost.com:10.77.77.77 # test ACME server (peeble)
    ports:
      - "80:80"
      - "443:443"
      - "5002:5002" # Needed for HTTP challenge
    image: "traefik:v2.0.0-rc3-alpine"
    command: >
      /bin/sh -c 'update-ca-certificates && traefik
      --log.level=DEBUG
      --api.insecure=true
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
      --entrypoints.webhttpchallenge.address=:5002
      --certificatesresolvers.myresolver.acme.httpchallenge=true
      --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=webhttpchallenge
      --certificatesresolvers.myresolver.acme.caserver=https://acme.localhost.com:4001/dir
      --certificatesresolvers.myresolver.acme.email=test@localhost.com
      --certificatesresolvers.myresolver.acme.storage=/acme.json'
    volumes:
      - ./peeble/certs/pebble.minica.pem:/usr/local/share/ca-certificates/pebble.minica.pem:ro # import peeble RootCA
      - "./acme.json:/acme.json:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      bluenet:
        ipv4_address: 10.77.77.66

  whoami:
    image: "containous/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`mail.localhost.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    networks:
      bluenet:
        ipv4_address: 10.77.77.95


networks:
  bluenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.77.77.0/24

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local