version: "3.7"

services:

  ### Autorenew docker-mailserver part ###
  autorenew-mailserver-certs:
    build:
      context: ./../
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./acme.json:/tmp/traefik/acme.json:ro" # acme.json from Traefik
    environment:
      - TRAEFIK_VERSION=2
      - CERTS_SOURCE=file
      - DOMAINS=mail.localhost.com
    networks:
      bluenet:
        ipv4_address: 10.77.77.88

  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: localhost.com
    labels:
      - "mailserver-traefik-autorenew-domain=mail.localhost.com"
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`mail.localhost.com`)" # traefik ACME will handle creation of certificates for this domain
      - "traefik.http.routers.mail.entrypoints=websecure"
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./.mailserver-config/:/tmp/docker-mailserver/
      - ./.mailserver-config/dh-dovecot.pem:/etc/dovecot/dh.pem:ro # saving us computation
    env_file:
      - .mailserver.env
    networks:
      bluenet:
        ipv4_address: 10.77.77.44

  ### ACME test server ###
  pebble:
    image: letsencrypt/pebble
    command: pebble -config /test/my-pebble-config.json -dnsserver 10.77.77.22:8053
    ports:
      - 4001:4001  # ACME port
      - 15000:15000  # Management port
    environment:
      - PEBBLE_VA_NOSLEEP=1
    extra_hosts:
      - acme.localhost.com:10.77.77.77 # test ACME server (peeble)
    volumes:
      - ./peeble/certs/:/test/certs/:ro # import peeble RootCA
      - ./peeble/peeble-config.json:/test/my-pebble-config.json:ro
    networks:
      bluenet:
        ipv4_address: 10.77.77.77
    depends_on:
      - challtestsrv
  challtestsrv: # dns server for pebble
    image: letsencrypt/pebble-challtestsrv:latest
    command: pebble-challtestsrv -defaultIPv6 "" -defaultIPv4 10.77.77.66 # mock DNS responses to traefik
    ports:
      - 8055:8055  # HTTP Management API
    networks:
      bluenet:
        ipv4_address: 10.77.77.22

  ### Traefik part ###
  traefik:
    image: "traefik:v2.2"
    extra_hosts:
      - acme.localhost.com:10.77.77.77 # test ACME server (peeble)
    command: /bin/sh -c 'update-ca-certificates && traefik --configFile=/etc/traefik/conf/acme.toml'
    volumes:
      - ./peeble/certs/pebble.minica.pem:/usr/local/share/ca-certificates/pebble.minica.pem:ro # import peeble RootCA
      - "./traefik.v2.file.toml:/etc/traefik/conf/acme.toml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/tmp/acme/acme.json:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
    ports:
      - "80:80"
      - "443:443"
      - "5002:5002" # Needed for HTTP challenge
    networks:
      traefik-public:
      bluenet:
        ipv4_address: 10.77.77.66


networks:
  traefik-public:
  bluenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.77.77.0/24

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local