version: "3.7"

services:

  ### Autorenew docker-mailserver part ###
  autorenew-mailserver-certs:
    build:
      context: ./../
      dockerfile: Dockerfile
    labels:
      - "traefik.frontend.rule=Host:mail.localhost.com" # traefik ACME will handle creation of certificates for this domain
      - traefik.frontend.redirect.replacement=http://localhost.com/ # redirect access to smtp/imap domain to and other domain (e.g. webmail)
      - traefik.frontend.redirect.regex=.*
      - traefik.port=8080 # dummy port, used only to trigger certificate renewal
      - traefik.enable=true
      - traefik.frontend.entryPoints=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssl:/tmp/ssl
    environment:
      - TRAEFIK_VERSION=1
      - CERTS_SOURCE=consul
      - DOMAIN=mail.localhost.com
      - KV_ENDPOINTS=[consul-leader:8500]
    depends_on:
      - traefik
    networks:
      bluenet:
        ipv4_address: 10.77.77.88

  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: localhost.com
    labels:
      - "mailserver-traefik-autorenew-domain=mail.localhost.com"
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./.mailserver-config/:/tmp/docker-mailserver/
    env_file:
      - .mailserver.env
    networks:
      bluenet:
        ipv4_address: 10.77.77.44

  ### ACME test server ###
  pebble:
    image: letsencrypt/pebble
    command: pebble -config /test/my-pebble-config.json -dnsserver 10.77.77.22:8053
    ports:
      - 4001:4001  # ACME port
      - 15000:15000  # Management port
    environment:
      - PEBBLE_VA_NOSLEEP=1
    extra_hosts:
      - acme.localhost.com:10.77.77.77 # test ACME server (peeble)
    volumes:
      - ./peeble/certs/:/test/certs/:ro # import peeble RootCA
      - ./peeble/peeble-config.json:/test/my-pebble-config.json:ro
    networks:
      bluenet:
        ipv4_address: 10.77.77.77
    depends_on:
      - challtestsrv
  challtestsrv: # dns server for pebble
    image: letsencrypt/pebble-challtestsrv:latest
    command: pebble-challtestsrv -defaultIPv6 "" -defaultIPv4 10.77.77.66 # mock DNS responses to traefik
    ports:
      - 8055:8055  # HTTP Management API
    networks:
      bluenet:
        ipv4_address: 10.77.77.22

  ### Traefik part ###
  traefik:
    image: traefik:v1.7-alpine
    command: /bin/sh -c 'update-ca-certificates && traefik --configFile=/etc/traefik/conf/acme.toml'
    restart: unless-stopped
    extra_hosts:
      - acme.localhost.com:10.77.77.77 # test ACME server (peeble)
    volumes:
      - ./peeble/certs/pebble.minica.pem:/usr/local/share/ca-certificates/pebble.minica.pem:ro # import peeble RootCA
      - "./acme.consul.toml:/etc/traefik/conf/acme.toml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
      - "443:443"
      - "5002:5002" # Needed for HTTP challenge
    expose:
      - "8080"
    labels:
      - "traefik.port=8080"
      - "traefik.backend=traefikception"
      - "traefik.frontend.rule=Host:traefik.localhost.com"
      - "traefik.enable=true"
    depends_on:
      - consul-leader
      - pebble
    networks:
      bluenet:
        ipv4_address: 10.77.77.66

  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    labels:
      - "traefik.frontend.rule=Host:consul.localhost.com"
      - traefik.enable=true
      - traefik.port=8500
      - traefik.frontend.entryPoints=https
    networks:
      bluenet:
        ipv4_address: 10.77.77.62

networks:
  bluenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.77.77.0/24

volumes:
  consul-data-leader:
    driver: local
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local