version: "3.7"

services:

  ### Autorenew docker-mailserver part ###
  mailserver-traefik:
    build:
      context: ./../
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./acme.json:/tmp/traefik/acme.json:ro" # acme.json from Traefik
    environment:
      - TRAEFIK_VERSION=1
      - CERTS_SOURCE=file
      - DOMAINS=mail.localhost.com,mailserver2.localhost.com
    networks:
      - internal

  mailserver:
    image: mailserver/docker-mailserver:latest
    hostname: mail
    domainname: localhost.com
    labels:
      - "mailserver-traefik.renew.domain=mail.localhost.com"
      - "traefik.frontend.rule=Host:mail.localhost.com" # traefik ACME will handle creation of certificates for this domain
      - "traefik.frontend.redirect.replacement=https://webmail.localhost.com/" # redirect access to smtp/imap domain to and other domain (e.g. webmail or autoconfig)
      - "traefik.frontend.redirect.regex=.*"
      - "traefik.enable=true"
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - maillogs:/var/log/mail
      - ./.mailserver-config/:/tmp/docker-mailserver/
      - ./.mailserver-config/dh-dovecot.pem:/etc/dovecot/dh.pem:ro # saving us computation
    env_file:
      - .mailserver.env
    environment:
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/var/mail-state/manual-ssl/cert
      - SSL_KEY_PATH=/var/mail-state/manual-ssl/key
    networks:
      bluenet:
        ipv4_address: 10.77.77.44

  ### ACME test server ###
  pebble:
    image: letsencrypt/pebble
    command: pebble -config /test/my-pebble-config.json -dnsserver 10.77.77.22:8053
    ports:
      - 4001:4001  # ACME port
      - 15000:15000  # Management port
    environment:
      - PEBBLE_VA_NOSLEEP=1
    extra_hosts:
      - acme.localhost.com:10.77.77.77 # test ACME server (peeble)
    volumes:
      - ./peeble/certs/:/test/certs/:ro # import peeble RootCA
      - ./peeble/peeble-config.json:/test/my-pebble-config.json:ro
    networks:
      bluenet:
        ipv4_address: 10.77.77.77
    depends_on:
      - challtestsrv
  challtestsrv: # dns server for pebble
    image: letsencrypt/pebble-challtestsrv:latest
    command: pebble-challtestsrv -defaultIPv6 "" -defaultIPv4 10.77.77.66 # mock DNS responses to traefik
    ports:
      - 8055:8055  # HTTP Management API
    networks:
      bluenet:
        ipv4_address: 10.77.77.22

  ### Traefik part ###
  traefik:
    image: traefik:v1.7-alpine
    command: /bin/sh -c 'update-ca-certificates && traefik --configFile=/etc/traefik/conf/acme.toml'
    extra_hosts:
      - acme.localhost.com:10.77.77.77 # test ACME server (peeble)
    volumes:
      - ./peeble/certs/pebble.minica.pem:/usr/local/share/ca-certificates/pebble.minica.pem:ro # import peeble RootCA
      - "./acme.file.toml:/etc/traefik/conf/acme.toml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/etc/traefik/conf/acme.json:rw"
    ports:
      - "80:80"
      - "443:443"
      - "5002:5002" # Needed for HTTP challenge
    expose:
      - "8080"
    labels:
      - "traefik.port=8080"
      - "traefik.backend=traefikception"
      - "traefik.frontend.rule=Host:traefik.localhost.com"
      - "traefik.enable=true"
    networks:
      bluenet:
        ipv4_address: 10.77.77.66


networks:
  internal: # no internet acess
    internal: true
  bluenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.77.77.0/24

volumes:
  maildata:
    driver: local
  maillogs:
    driver: local