
[serversTransport]
  rootCAs = [ "/usr/local/share/ca-certificates/pebble.minica.pem" ]

[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.http5002challenge]
    address = ":5002"
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.myresolver.acme]
  email = "test@traefik.io"
  storage = "/tmp/acme/acme.json"
  caServer = "https://acme.localhost.com:4001/dir"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "http5002challenge"


[log]
  level = "DEBUG"




[api]
  dashboard = true

[providers.docker]
    exposedByDefault = false
    network = "traefik-public"

